import Footer from "./footer/page.js";
import Navbar from "./navbar/page.js";
import Head from 'next/head'

export const metadata = {
  title: 'Portfolio of Jenny Nguyen Öberg',
  description: 'Generated by create next app',
}

export default function Layout({children}) {
  return (
    <div>
      <Head>
        <title>Portfolio of Jenny Nguyen Öberg</title>
        <meta name="description" content="Portfolio of Jenny Nguyen Öberg" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
      <Footer />
    </div>
  )
}
